# Public example configuration. Change locally before building a release APK.

[client]
host = 45.157.16.75
port = 7777
version = 0.3.7
name = Nick_Name
autoaim = 0

#password = changeme
[debug]
debug = false
online = true

[gui]
Font = Arial.ttf
FontSize = 30.0
FontOutline = 2
ChatPosX = 170.0
ChatPosY = 235.0
ChatSizeX = 1150.0
ChatSizeY = 220.0
ChatMaxMessages = 5
HealthBarWidth = 60.0
HealthBarHeight = 10.0
androidkeyboard = 0
VoiceChatEnable = true

